<a href="https://colab.research.google.com/github/QuentinGend/Wagon/blob/main/Quentin_Machine_Learning_Paris_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [281]:
import pandas as pd
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [282]:
df = pd.read_csv("ML_Paris24.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   game_year        357 non-null    int64  
 1   country          357 non-null    object 
 2   total_medal      357 non-null    int64  
 3   gdp_per_capita   357 non-null    object 
 4   population       357 non-null    object 
 5   democracy_index  357 non-null    float64
 6   host_city        357 non-null    int64  
 7   last_score       357 non-null    int64  
 8   log_gdp          357 non-null    float64
 9   log_pop          357 non-null    float64
dtypes: float64(3), int64(4), object(3)
memory usage: 28.0+ KB


In [283]:
df['previous_olympics'] = df.game_year - 4

In [284]:
df.head()

game_year     country  total_medal gdp_per_capita     population  \
0       1996   Argentina            3      15,570.00  35,389,360.00   
1       1996   Australia           41      34,960.00  18,211,850.00   
2       1996  Azerbaijan            1       2,625.00   7,949,107.00   
3       1996     Belarus           15       8,840.00  10,436,455.00   
4       1996     Belgium            6      28,905.00  10,123,230.00   

   democracy_index  host_city  last_score    log_gdp    log_pop  \
0             0.83          0           0   9.653101  17.381922   
1             0.89          0           0  10.461960  16.717583   
2             0.24          0           0   7.872836  15.888570   
3             0.45          0           0   9.087042  16.160816   
4             0.88          0           0  10.271770  16.130343   

   previous_olympics  
0               1992  
1               1992  
2               1992  
3               1992  
4               1992

In [285]:
df.isnull().sum()

game_year            0
country              0
total_medal          0
gdp_per_capita       0
population           0
democracy_index      0
host_city            0
last_score           0
log_gdp              0
log_pop              0
previous_olympics    0
dtype: int64

In [286]:
df_train, df_test = train_test_split(df, test_size=0.2, random_state=42, shuffle=True)

In [287]:
reg = LinearRegression()
X_train = df_train[["log_gdp", "log_pop", "democracy_index", "last_score", "host_city", "previous_olympics"]]
# X_train = df_train[["last_score", "previous_olympics"]]
# X_train = df_train[["log_gdp", "log_pop", "last_score", "host_city", "previous_olympics"]]
y_train = df_train[["total_medal"]]
reg.fit(X_train, y_train)

LinearRegression()

In [288]:
reg.intercept_

array([774.6557277])

In [289]:
reg.coef_

array([[ 3.611048  ,  2.4846046 , -2.97567424,  0.79773484, 25.00433726,
        -0.4218567 ]])

In [290]:
reg.score(X_train, y_train)

0.8308807180565848

In [291]:
import statsmodels.api as sm
import numpy as np
X = X_train
X = sm.add_constant(X)
model = sm.OLS(y_train, X)
results = model.fit()
results.params

const                774.655728
log_gdp                3.611048
log_pop                2.484605
democracy_index       -2.975674
last_score             0.797735
host_city             25.004337
previous_olympics     -0.421857
dtype: float64

In [292]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:            total_medal   R-squared:                       0.831
Model:                            OLS   Adj. R-squared:                  0.827
Method:                 Least Squares   F-statistic:                     227.6
Date:                Tue, 05 Sep 2023   Prob (F-statistic):          3.58e-104
Time:                        13:32:05   Log-Likelihood:                -1026.9
No. Observations:                 285   AIC:                             2068.
Df Residuals:                     278   BIC:                             2093.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const               774.6557    142.41

In [293]:
y_pred = reg.predict(X_train)
r2_score(y_train, y_pred)

0.8308807180565848

In [294]:
# X_test = df_test[["last_score", "previous_olympics"]]
X_test = df_test[["log_gdp", "log_pop", "democracy_index", "last_score", "host_city", "previous_olympics"]]
# X_test = df_test[["log_gdp", "log_pop", "last_score", "host_city", "previous_olympics"]]
y_test = df_test[["total_medal"]]
y_test_pred = reg.predict(X_test)
print(f"Predicted values for the test set: {y_test_pred}")

Predicted values for the test set: [[  4.31318768]
 [  9.15691695]
 [  1.31741465]
 [  6.38879354]
 [ 22.26613226]
 [  8.28563327]
 [  0.58352113]
 [ 15.21918484]
 [  2.44752645]
 [ 12.51473958]
 [ 24.92060154]
 [ 12.8407675 ]
 [  5.41480988]
 [ 15.04522178]
 [ 33.21096841]
 [  4.31677454]
 [ 61.80866719]
 [ 29.94341167]
 [ 31.89301523]
 [ 12.49757825]
 [ 25.61597032]
 [ 41.72892677]
 [  3.68760809]
 [  8.08385591]
 [ 11.59817429]
 [ 40.61511245]
 [ 13.76055005]
 [ 39.71940087]
 [ 16.19222472]
 [ 11.58856103]
 [  9.89117594]
 [  4.81488821]
 [  4.0952017 ]
 [  9.58574106]
 [  9.76889668]
 [ 12.99024397]
 [ 10.08513263]
 [107.03840987]
 [ 24.08374963]
 [ 61.60366319]
 [ 64.0543933 ]
 [  7.72528854]
 [ 17.17036157]
 [ 12.45760237]
 [  7.77829094]
 [ 29.55546358]
 [ 12.55976539]
 [ 12.43333638]
 [  9.35763176]
 [ 10.97712567]
 [ 15.39098791]
 [  3.7108399 ]
 [  9.90577706]
 [  8.43552022]
 [  0.80643928]
 [  6.17460996]
 [  5.94511687]
 [ 40.91618546]
 [ 25.72826104]
 [  7.75991792]
 [  2

In [295]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_test_pred)

5.641914447176812

In [396]:
X_test_France = [[10.7143, 17.983, 0.87, 33, 1, 2020]]
#X_test = df_test[["log_gdp", "log_pop", "democracy_index", "last_score", "host_city", "previous_olympics"]]

In [397]:
X_test_France

[[10.7143, 17.983, 0.87, 33, 1, 2020]]

In [298]:
X_test_USA = [[10.7143, 17.983, 0.872, 33, 1, 2020]]

In [398]:
reg.predict(X_test_France)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[54.6164472]])

In [300]:
from sklearn.model_selection import KFold

In [301]:
kf = KFold(n_splits=5, random_state=42, shuffle=True)
print(kf)

KFold(n_splits=5, random_state=42, shuffle=True)


In [302]:
X = X_train.to_numpy()

In [303]:
y = y_train.to_numpy()

In [304]:
lr = LinearRegression()

In [305]:
mae_scores = []
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    mae_scores.append(mean_absolute_error(y_test, y_pred))

In [306]:
np.mean(mae_scores)

6.059525569025676

In [307]:
k_test_France = lr.predict([[10.7143, 17.983, 0.872, 33, 1, 2020]])
k_test_France

array([[54.15490875]])

In [308]:
k_test_USA = lr.predict([[11.061, 19.635, 0.81, 113, 0, 2020]])
k_test_USA

array([[98.68217846]])

In [309]:
k_test_Russia = lr.predict([[10.238, 18.796, 0.25, 70, 0, 2020]])
k_test_Russia

array([[60.64827569]])

In [310]:
k_test_Germany = lr.predict([[10.881, 18.239, 0.87, 37, 0, 2020]])
k_test_Germany

array([[34.01318831]])

In [311]:
k_test_China = lr.predict([[9.775, 21.078, 0.08, 88, 0, 2020]])
k_test_China

array([[79.30854412]])

In [312]:
k_test_Italy = lr.predict([[10.643, 17.897, 0.85, 40, 0, 2020]])
k_test_Italy

array([[34.631689]])

In [313]:
k_test_Australia = lr.predict([[10.815, 17.070, 0.85, 45, 0, 2020]])
k_test_Australia

array([[37.18258531]])

In [314]:
k_test_NewZealand = lr.predict([[10.666, 15.450, 0.88, 20, 0, 2020]])
k_test_NewZealand

array([[12.58390963]])

In [315]:
k_test_Ukraine = lr.predict([[9.468, 17.588, 0.51, 19, 0, 2020]])
k_test_Ukraine

array([[13.41532519]])

In [316]:
k_test_SouthKorea = lr.predict([[10.697, 17.763, 0.86, 20, 0, 2020]])
k_test_SouthKorea

array([[18.62273894]])

In [317]:
k_test_GB = lr.predict([[10.713, 18.024, 0.86, 65, 0, 2020]])
k_test_GB

array([[55.02775404]])

In [318]:
k_test_Japan = lr.predict([[10.616, 18.640, 0.84, 57, 0, 2020]])
k_test_Japan

array([[49.91309693]])

In [319]:
k_test_Canada = lr.predict([[10.776, 17.457, 0.85, 24, 0, 2020]])
k_test_Canada

array([[21.35823036]])

In [320]:
k_test_Netherlands = lr.predict([[10.944, 16.677, 0.86, 36, 0, 2020]])
k_test_Netherlands

array([[29.53659851]])

In [321]:
k_test_Brazil = lr.predict([[9.588, 19.183, 0.67, 20, 0, 2020]])
k_test_Brazil

array([[18.31246741]])

In [322]:
k_test_Hungary = lr.predict([[10.422, 16.088, 0.46, 20, 0, 2020]])
k_test_Hungary

array([[14.32385536]])

In [388]:
df2=pd.read_csv("ML_Paris2024_v2.csv")
df2['previous_olympics'] = df.game_year - 4
df2.head()

game_year     country  total_medal gdp_per_capita     population  \
0       1996   Argentina          3.0      15,570.00  35,389,360.00   
1       1996   Australia         41.0      34,960.00  18,211,850.00   
2       1996  Azerbaijan          1.0       2,625.00   7,949,107.00   
3       1996     Belarus         15.0       8,840.00  10,436,455.00   
4       1996     Belgium          6.0      28,905.00  10,123,230.00   

   democracy_index  host_city  last_score  log_gdp  log_pop  previous_olympics  
0             0.83          0           0    9.653   17.382             1992.0  
1             0.89          0           0   10.462   16.718             1992.0  
2             0.24          0           0    7.873   15.889             1992.0  
3             0.45          0           0    9.087   16.161             1992.0  
4             0.88          0           0   10.272   16.130             1992.0

In [399]:
df2 = df2[df2["game_year"]==2024]
df2.head()

game_year    country  total_medal gdp_per_capita     population  \
357       2024  Australia          NaN         64,600  26,439,111.00   
358       2024     Brazil          NaN         10,220    216,422,446   
359       2024     Canada          NaN         54,230     38,781,291   
360       2024     France          NaN         45,729     64,756,584   
361       2024    Germany          NaN         53,010     83,294,633   

     democracy_index  host_city  last_score  log_gdp  log_pop  \
357             0.86          0          45   11.076   17.090   
358             0.68          0          20    9.232   19.193   
359             0.85          0          24   10.901   17.473   
360             0.87          1          33   10.730   17.986   
361             0.86          0          37   10.878   18.238   

     previous_olympics  
357                NaN  
358                NaN  
359                NaN  
360                NaN  
361                NaN

In [390]:
df_country_2024 = df2.country.unique().tolist()
df_country_2024

['Australia',
 'Brazil',
 'Canada',
 'France',
 'Germany',
 'Great Britain',
 'Hungary',
 'Italy',
 'Japan',
 'Netherlands',
 'New Zealand',
 "People's Republic of China",
 'Republic of Korea',
 'Russian Federation',
 'Spain',
 'Ukraine',
 'United States of America']

In [401]:
df3 = df2.drop(columns=["game_year","country","total_medal","gdp_per_capita","population"])

In [402]:
df3["previous_olympics"] = 2020
df3

democracy_index  host_city  last_score  log_gdp  log_pop  \
357             0.86          0          45   11.076   17.090   
358             0.68          0          20    9.232   19.193   
359             0.85          0          24   10.901   17.473   
360             0.87          1          33   10.730   17.986   
361             0.86          0          37   10.878   18.238   
362             0.84          0          65   10.806   18.031   
363             0.45          0          20    9.948   16.134   
364             0.84          0          40   10.536   17.891   
365             0.83          0          57   10.505   18.630   
366             0.85          0          36   11.065   16.684   
367             0.89          0          20   10.786   15.470   
368             0.07          0          88    9.602   21.078   
369             0.81          0          20   10.458   17.763   
370             0.21          0          70    9.604   18.788   
371             0.87          0          17   10.389   17.677   
372             0.41          0          19    8.445   17.420   
373             0.82          0         113   11.316   19.644   

     previous_olympics  
357               2020  
358               2020  
359               2020  
360               2020  
361               2020  
362               2020  
363               2020  
364               2020  
365               2020  
366               2020  
367               2020  
368               2020  
369               2020  
370               2020  
371               2020  
372               2020  
373               2020

In [403]:
df4 = df3[["log_gdp", "log_pop", "democracy_index", "last_score", "host_city","previous_olympics"]]
df4.head()

log_gdp  log_pop  democracy_index  last_score  host_city  \
357   11.076   17.090             0.86          45          0   
358    9.232   19.193             0.68          20          0   
359   10.901   17.473             0.85          24          0   
360   10.730   17.986             0.87          33          1   
361   10.878   18.238             0.86          37          0   

     previous_olympics  
357               2020  
358               2020  
359               2020  
360               2020  
361               2020

In [404]:
test = df4.to_numpy()
test

array([[1.1076e+01, 1.7090e+01, 8.6000e-01, 4.5000e+01, 0.0000e+00,
        2.0200e+03],
       [9.2320e+00, 1.9193e+01, 6.8000e-01, 2.0000e+01, 0.0000e+00,
        2.0200e+03],
       [1.0901e+01, 1.7473e+01, 8.5000e-01, 2.4000e+01, 0.0000e+00,
        2.0200e+03],
       [1.0730e+01, 1.7986e+01, 8.7000e-01, 3.3000e+01, 1.0000e+00,
        2.0200e+03],
       [1.0878e+01, 1.8238e+01, 8.6000e-01, 3.7000e+01, 0.0000e+00,
        2.0200e+03],
       [1.0806e+01, 1.8031e+01, 8.4000e-01, 6.5000e+01, 0.0000e+00,
        2.0200e+03],
       [9.9480e+00, 1.6134e+01, 4.5000e-01, 2.0000e+01, 0.0000e+00,
        2.0200e+03],
       [1.0536e+01, 1.7891e+01, 8.4000e-01, 4.0000e+01, 0.0000e+00,
        2.0200e+03],
       [1.0505e+01, 1.8630e+01, 8.3000e-01, 5.7000e+01, 0.0000e+00,
        2.0200e+03],
       [1.1065e+01, 1.6684e+01, 8.5000e-01, 3.6000e+01, 0.0000e+00,
        2.0200e+03],
       [1.0786e+01, 1.5470e+01, 8.9000e-01, 2.0000e+01, 0.0000e+00,
        2.0200e+03],
       [9.6020e+00, 2

In [407]:
for country in range(len(df_country_2024)):
  value = df_country_2024[country]
  print(f"the total medal for {value} is : {lr.predict([test[country]]).round(0)}")

the total medal for Australia is : [[38.]]
the total medal for Brazil is : [[17.]]
the total medal for Canada is : [[22.]]
the total medal for France is : [[54.]]
the total medal for Germany is : [[34.]]
the total medal for Great Britain is : [[55.]]
the total medal for Hungary is : [[13.]]
the total medal for Italy is : [[34.]]
the total medal for Japan is : [[49.]]
the total medal for Netherlands is : [[30.]]
the total medal for New Zealand is : [[13.]]
the total medal for People's Republic of China is : [[79.]]
the total medal for Republic of Korea is : [[18.]]
the total medal for Russian Federation is : [[58.]]
the total medal for Spain is : [[15.]]
the total medal for Ukraine is : [[9.]]
the total medal for United States of America is : [[100.]]
